services:
    frontend:
        container_name: front-app
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/app
            - /app/node_modules 
        ports:
            - "8000:3000"
    backend:
        container_name: back-app
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app
        ports:
            - "8080:8080"
    db:
        container_name: database
        build:
            context: ./database
            dockerfile: Dockerfile
        volumes:
            - database-volumes:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
            MYSQL_USER: spring
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"

volumes:
    database-volumes: