version: '3'

services:
    frontend:
        container_name: front-app
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/app
            - /app/node_modules 
        ports:
            - "8000:3000"
    backend:
        container_name: back-app
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app
        ports:
            - "8080:8080"